### ISSUE TITLE
Enable profile editing functionality to allow candidates to update their information as needed.

### ISSUE THREAD

**Issue by hannaa12** [kin-kins/Web_Warriors-SOEN6011summer2023#10]
User Story: #20 

### Acceptance Criteria
1. Edit profile feature is available for candidates to edit their information and it works properly.
2. Information once edited is updated correctly in the database.

**Comment by Shefali-Upadhyaya** [comment]
This feature was implemented. Linked the pull request. Hence, closing it manually.
