### ISSUE TITLE
Develop an eligibility criteria suggestion feature where the candidate is informed if he/she is eligible to apply to a certain job post

### ISSUE THREAD

**Issue by ionathomas** [kin-kins/Web_Warriors-SOEN6011summer2023#101]
Epic: #100 

### Acceptance Criteria:
1. The candidate is able to see if they are eligible for a job post based on their skills.
2. The candidate is able to see if they are eligible for a job post based on their experience.

**Comment by Shefali-Upadhyaya** [comment]
This feature has been implemented
