### ISSUE TITLE
Create a resume upload feature that allows candidates to select and upload their resume files.

### ISSUE THREAD

**Issue by hannaa12** [kin-kins/Web_Warriors-SOEN6011summer2023#12]
User Story: #21 

### Acceptance Criteria
1. Candidate profile has an upload button.
2. Upload button is able to select and upload files.
3. Candidate profile is saved with uploaded file.

**Comment by Shefali-Upadhyaya** [comment]
This issue is covered with pull request #82 . Hence, manually closing it.
