### ISSUE TITLE
Develop a mechanism to store and associate the uploaded resume with the candidate's profile.

### ISSUE THREAD

**Issue by hannaa12** [kin-kins/Web_Warriors-SOEN6011summer2023#13]
User Story: #21 

### Acceptance Criteria
1. The uploaded resume is stored into the database appropriately.
2. The uploaded resume is uploaded and mapped to the correct candidate in the database.

**Comment by Shefali-Upadhyaya** [comment]
This issue is covered with pull request #82. Hence, manually closing it.
