### ISSUE TITLE
Implement a resume download feature for employers to access and review the candidate's qualifications.

### ISSUE THREAD

**Issue by hannaa12** [kin-kins/Web_Warriors-SOEN6011summer2023#15]
User Story: #28  

### Acceptance Criteria
1. Resume shown is the candidate's resume.
2. The resume is stored in the database without any corruption.
3. The resume can be downloaded by fetching it from the database.

**Comment by Shefali-Upadhyaya** [comment]
This feature is part of #28 for employers and employers is not yet implemented, hence moving this to the next sprint.
