### ISSUE TITLE
Develop backend logic to validate user input, check for existing accounts, and securely store user registration information.

### ISSUE THREAD

**Issue by hannaa12** [kin-kins/Web_Warriors-SOEN6011summer2023#2]
User Story: #18 

### Acceptance Criteria
1. The data is sent to the database without any issues.
2. Password is encrypted correctly.
3. The relevant data is written into the appropriate DB tables and fields.

**Comment by Shefali-Upadhyaya** [comment]
This feature has been implemented with #84. Hence, manually closing it.
