### ISSUE TITLE
Develop an application submission feature that allows candidates to apply for job offers by submitting their profile or resume.

### ISSUE THREAD

**Issue by Shefali-Upadhyaya** [kin-kins/Web_Warriors-SOEN6011summer2023#57]
User Story: #31 

### Acceptance Criteria
1. The user is able to share the resume with the correct job post.
2. The relevant details related to the candidate are stored appropriately in the database.

**Comment by ionathomas** [comment]
This ticket has been completed. Manually closing the ticket
