### ISSUE TITLE
Design and develop a candidate profile page with fields for personal information, education, skills, and experience.

### ISSUE THREAD

**Issue by hannaa12** [kin-kins/Web_Warriors-SOEN6011summer2023#8]
User Story: #20 

### Acceptance Criteria
1. Candidate profile has all the necessary fields to build a profile - personal information, education, skills, and experience.
2. Both frontend and backend have the same set of fields to store information.

**Comment by ionathomas** [comment]
Only the personal information part has been implemented. The rest of the features will be implemented in the next Sprint.
