### ISSUE TITLE
Implement form validation to ensure the required fields (like personal information, education experience, skills and experience) are filled out and validate the input format.

### ISSUE THREAD

**Issue by hannaa12** [kin-kins/Web_Warriors-SOEN6011summer2023#9]
User Story: #20 

### Acceptance Criteria
1. The fields are not empty.
2. The data is sent to the database.
3. The data is written into the appropriate DB tables in the appropriate fields.

**Comment by ionathomas** [comment]
This feature has been partially implemented. The rest of the implementation will be carried out in the next Sprint.
